[package]
name = "cli_web_scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13.1", features = ["json"] }
scraper = "0.25.0"
tokio = { version = "1.49.0", features = ["full"] }
trpl = "0.3.0"