[package]
name = "cli_task_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
serde_json = "1.0.145"
serde = { version = "1.0", features = ["derive"] }
